### PR TITLE
Add Inventory and Item Page

### LINKED ISSUE #20: 22. Staff can remove a product from the product listing page

### LINKED ISSUE #21: 23. Staff can update production information from the product listing page

### LINKED ISSUE #22: 24. Staff can filter products on the product listing page

### LINKED ISSUE #48: 21. Staff can add a new product to the products listing page

### LINKED ISSUE #101: 21. Staff can view individual product information
Staff clicks on individual item in the inventory and is brought to an edit page.

### PR DESCRIPTION
**Pull request by dLamSlo8**
# Summary
Adds an inventory page for staff. The page has filtering capabilities via the categories. Staff can add a product by clicking on "Add Item" and update or delete a product by first clicking on an individual item ID. Within this "Item" page, one can edit a product's fields and delete a product. All input requires generic validation. Changing a product in any way (i.e. CRUD) should see immediate changes upon being redirected to the inventory page. 

# Missing Features
Categories for products are not yet implemented into the CRUD operations. They cannot be changed for now. 

# QA
- In the inventory page (accessed manually via /admin/inventory) check to see that filtering categories works as expected (i.e. selecting a category only shows products of that category, no category selected shows all products, etc.)
- Click on "Add Item" to see that it brings you to an unfilled Item page. This page will not have a "Delete" button. Verify that the input is required and leaving any empty prompts you to fill it in. This is not the case for "Cancel". That should redirect only.
- In the inventory page, verify that selecting a product's ID leads you to an "Item" page with the appropriate product information.
- Verify that, on a populated "Item" page, you can edit fields and upon clicking "Save Item" you are redirected to "Inventory" and see the changes immediately. Same goes for clicking "Delete Item".

Closes #48 
Closes #101
Closes #22 
Closes #21 
Closes #20

### CODE REVIEW

**Comment by gmedinak** [comment]
The loading indicator/spinner does not work yet.
image

**Comment by colebemis** [comment]
@dLamSlo8 Looks like you have a lot of TypeScript compiler errors:

image

You mind trying to fix those before we merge this in?

**Comment by colebemis** [comment]
Any errors that you can't figure out, we can debug in class.

**Comment by colebemis** [comment]
Tested the functionality. Everything works as expected. We should add e2e tests, maybe in a separate pull though.

**Pull request merged**
