### PR TITLE
Checkout + Confirmation + Cart

### LINKED ISSUE #30: 12. Customers can purchase product(s) that have been added to their cart.
The checkout button on the cart pop-up will lead to the checkout page.

### LINKED ISSUE #31: 13. Customers must add their name and email at the checkout page.

### LINKED ISSUE #32: 13. Customers must add their billing information consisting of an editable payment method and billing address at the checkout page.
The billing info allows for adding additional payment methods, which will most likely be a pop-up.

### LINKED ISSUE #33: 13. Customers must add a shipping type and shipping address at the checkout page.
If a customer chooses "To Address" instead of "To Store" for shipping type, they must enter a shipping address, otherwise it is not necessary.

### LINKED ISSUE #122: Order status/confirmation page
We need to add a `/status/:productId` route that thanks the customer for their order and shows them the status of the order. We want to redirect to this page after successful checkout.

### PR DESCRIPTION
**Pull request by svmadiraju**
## Summary
This pull request closes #30, closes #31, closes #32, closes #33, closes #122.

This is a fat PR for a lot of new stuff - sorry for the size but I had no choice with this one given the time constraints. 

- Checkout page is completed, user can fill out the form and create an Order.
- Checkout is followed by the Confirmation page which verifies that the Order was placed.
- Cart page was also revamped to look less torturous on the eyes, please check it out!

### Package Changes
- Added [VeeValidate](https://baianat.github.io/vee-validate/), a neat form validation framework that makes sure forms are filled somewhat correctly. Being used for the the checkout form, just some basic drop-in front-end validation to make it seem a bit more legitimate.
- Run `npm install` from within `/client` directory

## Known Issues
- The confirmation page currently doesn't work if you are not logged in - this is because querying orders requires admin access/auth token. Any ideas on what to do about this?

### Checkout - Test Cases
- [x] Form cannot be submitted until all fields are filled
- [x] Form cannot be submitted until all fields are (somewhat) correctly filled with the right type of text
- [x] Error message displayed under each field that is incorrectly filled
- [x] When there are errors with fields, an error message displayed at the top of the form, directing user to correct the errors
- [x] Successfully submitting the form results in a confirmation message
- [x] Successfully submitting the form is reflected by a new order entry in the DB
- [x] Order Summary accurately reflects carts' products and pricing 
- [x] Making an Order results in an Inventory change for the purchased Product(s)
- In general, just try messing with the form and see if anything terrible happens (hopefully not).

### Checkout - Test Cases
- [x] Customer's name is accurately displayed in a confirmation message
- [x] Order status is accurately displayed

### CODE REVIEW

**Comment by colebemis** [comment]
Maybe we should just ask for `Name` instead of `First name` + `Last name` to match the datamodel.
image

**Comment by colebemis** [comment]
We still need to handle delivery and pick up

**Comment by colebemis** [comment]
Need address line 2

**Comment by colebemis** [comment]
To do:
- [ ] Handle delivery and pick up
- [ ] Add address line 2
- [ ] Fix stretching cart

**Comment by kmyzhang** [comment]
A bug occurs when I typed a proper city but it gives me the error message of "The Billing City field may only contain alphabetic characters."

**Comment by svmadiraju** [comment]
> A bug occurs when I typed a proper city but it gives me the error message of "The Billing City field may only contain alphabetic characters."

Fixed!

**Pull request merged**
