### PR TITLE
Add SiteInfo structures to database

### LINKED ISSUE #112: Update database and API to handle storing site information

### PR DESCRIPTION
**Pull request by gmedinak**
## Summary
This pull request updates the data model to hold site information, adds resolvers, and adds a .gql query for site information

### Package Changes
No package changes.

### Data Model Changes
- New `Hours` database object with fields for day, index (ordering), opening time, and closing time.
- New `Section` database object with fields for title and content
- New `SiteInfo` database object with fields for contact information, hours, and home page content
- [X] I have updated the [Database model](https://whimsical.co/7PBV8ZYSoxCeq6V4dUw2Sz) with all changes I am proposing with this Pull Request.
- [X] I have updated the [Requirements Document](https://docs.google.com/document/d/1HpaTuRBecx1ZbhxYL6glrHLT2Lg676OVGS2v6zB32JM/edit?usp=sharing) with all changes I am proposing with this Pull Request.

### Known Issues
- Duplicate Hours can be created when attempting to create hours from within the updateSiteInfo mutation. Workaround: make Hours with createHours mutation and then connect with updateSiteInfo.

### Test Cases
- [x] Run `npm test` from the `/server` directory and ensure that all test cases pass
- [x] Verify that the `siteInfo` query shows all the SiteInfo data in the local playground
- [x] Using the `updateSiteInfo` mutation, verify that phone can be updated in local playground
- [x] Using the `updateSiteInfo` mutation, verify that email can be updated in local playground
- [x] Using the `updateSiteInfo` mutation, verify that about (content) can be updated in local playground
- [x] Using the `updateSiteInfo` mutation, verify that services (content list) can be updated in local playground
- [x] Using the `updateSiteInfo` mutation, verify that hours can be created in local playground
- [x] Using the `updateSiteInfo` mutation, verify that hours can be updated in local playground
- [x] Using the `updateSiteInfo` mutation, verify that hours can be deleted in local playground

### User Acceptance Tests
- [x] I updated the [UAT Spreadsheet](https://docs.google.com/spreadsheets/d/1-unNcLQL7Nr2V69aXBpQKMH-Uv7lJhNOD3K-V7wv5Ik/edit?usp=sharing "UAT Spreadsheet") with tests for all proposed feature in this PR.

Closes #112

### CODE REVIEW

**Comment by dLamSlo8** [comment]
It says I'm not authorized to update so I'm assuming I got kicked LOL

**Comment by dLamSlo8** [comment]
w

**Comment by colebemis** [comment]
@dLamSlo8 Why did you close this?

**Comment by dLamSlo8** [comment]
oh what my bad accident

**Comment by kmyzhang** [comment]
Do we need a title field for section?

**Comment by gmedinak** [comment]
Great question @kmyzhang ! Probably not. That has been removed now.

**Pull request merged**
